- name: Install Basic Packages
  ansible.builtin.apt:
    name:
      - tree
      - cmake
      - xclip
      - build-essential
      - ansible-lint
      - zip
      - unzip
      - libreadline-dev
      - openssl
      - curl
      - gcc
      - libbz2-dev
      - libev-dev
      - libffi-dev
      - libgdbm-dev
      - liblzma-dev
      - libncurses-dev
      - libreadline-dev
      - libsqlite3-dev
      - libssl-dev
      - make
      - tk-dev
      - wget
      - git
      - zlib1g-dev
