- name: Install stow
  ansible.builtin.apt:
    name:
      - stow

- name: Clone dotfiles repository with specific tag
  ansible.builtin.git:
    repo: "{{ app_repository }}"
    dest: "{{ app_home_path }}"
    refspec: "{{ app_branch }}"
    force: true

- name: Setup Permissions
  ansible.builtin.file:
    state: directory
    recurse: true
    path: "{{ app_home_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Delete Files
  changed_when: false
  become: false
  ansible.builtin.shell: |
    {{ file_delete_setup }}
  args:
    executable: /bin/bash

- name: Configure Stow
  become: false
  register: configure_stow
  changed_when: false
  ansible.builtin.shell: "stow --dir={{ app_home_path }} --target={{ user_home_path }} ./"
  args:
    executable: /bin/bash
