- name: Install Plugin
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - plugin
      - add
      - golang
      - https://github.com/asdf-community/asdf-golang.git

- name: Install Latest Version
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - install
      - golang
      - 1.23.3

- name: Define Global Version
  become: false

  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - global
      - golang
      - 1.23.3
