- name: Install Plugin
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - plugin
      - add
      - spring-boot
      - https://github.com/joschi/asdf-spring-boot.git

- name: Install Latest Version
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - install
      - spring-boot
      - 3.3.6

- name: Define Global Version
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - global
      - spring-boot
      - 3.3.6
