- name: Install Plugin
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - plugin
      - add
      - maven
      - https://github.com/halcyon/asdf-maven.git

- name: Install Latest Version
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - install
      - maven
      - 3.9.9

- name: Define Global Version
  become: false
  ansible.builtin.command:
    argv:
      - "{{ binary_source_path }}"
      - global
      - maven
      - 3.9.9
