- name: Install ASDF
  ansible.builtin.include_tasks: install_asdf.yaml

- name: Install Java
  ansible.builtin.include_tasks: install_java.yaml

- name: Install Golang
  ansible.builtin.include_tasks: install_golang.yaml

- name: Install Lua
  ansible.builtin.include_tasks: install_lua.yaml

- name: Install Maven
  ansible.builtin.include_tasks: install_maven.yaml

- name: Install NodeJS
  ansible.builtin.include_tasks: install_node.yaml

- name: Install Python
  ansible.builtin.include_tasks: install_python.yaml

- name: Install SpringBoot
  ansible.builtin.include_tasks: install_springboot.yaml
