- name: Install Homebrew prerequisites (curl)
  ansible.builtin.apt:
    name:
      - curl

- name: Clone Homebrew repository
  ansible.builtin.git:
    repo: "{{ app_repository_url }}"
    dest: "{{ app_tmp_path }}"
    refspec: "{{ app_branch }}"
    force: true

- name: Run Homebrew installation script
  become: false
  changed_when: false
  ansible.builtin.shell: |
    export NONINTERACTIVE=1 && export HOMEBREW_PREFIX={{ app_home }}  && {{ app_tmp_path }}/install.sh
  args:
    executable: /bin/bash

- name: Create Homebrew bash completion file
  ansible.builtin.copy:
    dest: "{{ app_bash_completition_path }}"
    content: |
      {{ app_bash_completition_content }}
    owner: root
    group: root
    mode: "0555"

- name: Install yq, ripgrep, starship, and asdf with Homebrew
  become: false
  changed_when: false
  ansible.builtin.shell: |
    {{ app_binary }} install yq ripgrep starship asdf
  args:
    executable: /bin/bash


- name: Add asdf initialization to .bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: '. "$(brew --prefix asdf)/libexec/asdf.sh"'
    insertafter: EOF
    state: present
