app_name: asdf
app_home: "/var/lib/{{ app_name }}"
app_version: "0.14.1"
app_repository_url: "https://github.com/asdf-vm/asdf/archive/refs/tags/v{{ app_version }}.zip"
app_tmp_file: "/tmp/{{ app_name }}.zip"
app_temp_path: "/tmp/{{ app_name }}"
binary_source_path: "{{ app_home }}/bin/{{ app_name }}"
binary_dest_path: "/usr/bin/{{ app_name }}"
app_bash_completition_path: /etc/profile.d/{{ app_name }}.sh
app_bash_completition_content: |
  #!/bin/bash
  # Global environment configuration for asdf
  export ASDF_DIR={{ app_home }}
  . $ASDF_DIR/asdf.sh
  . $ASDF_DIR/completions/asdf.bash
