- name: Ensure tmux plugins directory permissions
  ansible.builtin.file:
    path: "{{ tmux_plugins_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    recurse: true
    mode: "0750"

- name: Clone tmux plugin manager (TPM) repository
  ansible.builtin.git:
    repo: "{{ tmux_repository }}"
    dest: "{{ tmux_plugins_path }}"
    refspec: "{{ tmux_version }}"
    force: true

- name: Ensure tmux configuration directory permissions
  ansible.builtin.file:
    path: "{{ tmux_default_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    state: directory
    recurse: true
    mode: "0750"
