- name: Install YQ and Ripgrep
  become: false
  register: install_homebrew
  changed_when: install_homebrew.rc != 0
  ansible.builtin.shell: install yq ripgrep starship
  args:
    executable: /home/linuxbrew/.linuxbrew/bin/brew


