- name: Install prerequistes
  ansible.builtin.apt:
    name:
      - build-essential

- name: Download NVIM tar file
  ansible.builtin.get_url:
    url: "{{ app_repository_url }}"
    dest: "{{ app_tmp_file }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Create tmp NVIM directory
  ansible.builtin.file:
    state: directory
    path: "{{ app_temp_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Extract NVIM archive to temporary path
  ansible.builtin.unarchive:
    src: "{{ app_tmp_file }}"
    dest: "{{ app_temp_path }}"
    remote_src: true

- name: Create NVIM directory
  ansible.builtin.file:
    state: directory
    path: "{{ app_home_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Install Nvim To Correct Folder
  ansible.builtin.copy:
    remote_src: true
    src: "{{ app_temp_path }}/nvim-linux64/"
    dest: "{{ app_home_path }}/"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Creates Symlink
  ansible.builtin.file:
    state: link
    src: "{{ binary_source_path }}"
    dest: "{{ binary_dest_path }}"
    owner: "{{ ansible_env.SUDO_USER }}"
    group: "{{ ansible_env.SUDO_USER }}"
    mode: "0750"

- name: Clean Up NVIM
  block:
    - name: Remove Temp Folder
      ansible.builtin.file:
        state: absent
        path: "{{ app_temp_path }}"
    - name: Remove Temp File
      ansible.builtin.file:
        state: absent
        path: "{{ app_tmp_file }}"
